# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libxdpd_mgmt_py_native', [dirname(__file__)])
        except ImportError:
            import _libxdpd_mgmt_py_native
            return _libxdpd_mgmt_py_native
        if fp is not None:
            try:
                _mod = imp.load_module('_libxdpd_mgmt_py_native', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libxdpd_mgmt_py_native = swig_import_helper()
    del swig_import_helper
else:
    import _libxdpd_mgmt_py_native
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class hola(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, hola, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, hola, name)
    __repr__ = _swig_repr
    def py_sum_test(self, *args): return _libxdpd_mgmt_py_native.hola_py_sum_test(self, *args)
    def __init__(self): 
        this = _libxdpd_mgmt_py_native.new_hola()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libxdpd_mgmt_py_native.delete_hola
    __del__ = lambda self : None;
hola_swigregister = _libxdpd_mgmt_py_native.hola_swigregister
hola_swigregister(hola)

class port_manager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, port_manager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, port_manager, name)
    __repr__ = _swig_repr
    __swig_getmethods__["exists"] = lambda x: _libxdpd_mgmt_py_native.port_manager_exists
    if _newclass:exists = staticmethod(_libxdpd_mgmt_py_native.port_manager_exists)
    __swig_getmethods__["is_vlink"] = lambda x: _libxdpd_mgmt_py_native.port_manager_is_vlink
    if _newclass:is_vlink = staticmethod(_libxdpd_mgmt_py_native.port_manager_is_vlink)
    __swig_getmethods__["get_vlink_pair"] = lambda x: _libxdpd_mgmt_py_native.port_manager_get_vlink_pair
    if _newclass:get_vlink_pair = staticmethod(_libxdpd_mgmt_py_native.port_manager_get_vlink_pair)
    __swig_getmethods__["list_available_port_names"] = lambda x: _libxdpd_mgmt_py_native.port_manager_list_available_port_names
    if _newclass:list_available_port_names = staticmethod(_libxdpd_mgmt_py_native.port_manager_list_available_port_names)
    def __init__(self): 
        this = _libxdpd_mgmt_py_native.new_port_manager()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libxdpd_mgmt_py_native.delete_port_manager
    __del__ = lambda self : None;
port_manager_swigregister = _libxdpd_mgmt_py_native.port_manager_swigregister
port_manager_swigregister(port_manager)

def port_manager_exists(*args):
  return _libxdpd_mgmt_py_native.port_manager_exists(*args)
port_manager_exists = _libxdpd_mgmt_py_native.port_manager_exists

def port_manager_is_vlink(*args):
  return _libxdpd_mgmt_py_native.port_manager_is_vlink(*args)
port_manager_is_vlink = _libxdpd_mgmt_py_native.port_manager_is_vlink

def port_manager_get_vlink_pair(*args):
  return _libxdpd_mgmt_py_native.port_manager_get_vlink_pair(*args)
port_manager_get_vlink_pair = _libxdpd_mgmt_py_native.port_manager_get_vlink_pair

def port_manager_list_available_port_names(include_blacklisted=False):
  return _libxdpd_mgmt_py_native.port_manager_list_available_port_names(include_blacklisted)
port_manager_list_available_port_names = _libxdpd_mgmt_py_native.port_manager_list_available_port_names

class plugin_manager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, plugin_manager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, plugin_manager, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _libxdpd_mgmt_py_native.new_plugin_manager()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libxdpd_mgmt_py_native.delete_plugin_manager
    __del__ = lambda self : None;
plugin_manager_swigregister = _libxdpd_mgmt_py_native.plugin_manager_swigregister
plugin_manager_swigregister(plugin_manager)

# This file is compatible with both classic and new-style classes.


